"""add agent_sessions, user_profiles, audit_logs

Revision ID: 0cb0ee18f542
Revises: 31e56328fb70
Create Date: 2026-06-29 20:42:13.746566
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0cb0ee18f542'
down_revision: Union[str, None] = '31e56328fb70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='操作用户 ID'),
    sa.Column('action', sa.String(length=100), nullable=False, comment='操作名称'),
    sa.Column('resource_type', sa.String(length=50), nullable=True, comment='资源类型'),
    sa.Column('resource_id', sa.String(length=100), nullable=True, comment='资源 ID'),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='操作详情'),
    sa.Column('ip_address', postgresql.INET(), nullable=True, comment='客户端 IP'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('agent_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户 ID'),
    sa.Column('course_id', sa.UUID(), nullable=False, comment='课程 ID'),
    sa.Column('intent', sa.String(length=20), nullable=False, comment='question/practice/diagnose/review/code_help'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending/running/waiting_human/completed/failed'),
    sa.Column('token_count', sa.Integer(), nullable=False, comment='Token 消耗量'),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=4), nullable=False, comment='预估成本（元）'),
    sa.Column('langgraph_thread_id', sa.String(length=100), nullable=True, comment='LangGraph checkpoint thread_id'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_sessions_course_id'), 'agent_sessions', ['course_id'], unique=False)
    op.create_index(op.f('ix_agent_sessions_user_id'), 'agent_sessions', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户 ID'),
    sa.Column('course_id', sa.UUID(), nullable=False, comment='课程 ID'),
    sa.Column('mastery_level', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='{"kp_path": mastery_rate, ...}'),
    sa.Column('weak_kps', postgresql.ARRAY(sa.Text()), nullable=True, comment='薄弱知识点 kp_path 数组'),
    sa.Column('common_mistakes', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='常见错误模式'),
    sa.Column('learning_style', sa.String(length=50), nullable=True, comment='visual/textual/practice'),
    sa.Column('total_qa_count', sa.Integer(), nullable=False, comment='累计问答次数'),
    sa.Column('total_practice_count', sa.Integer(), nullable=False, comment='累计练习次数'),
    sa.Column('avg_correct_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='平均正确率'),
    sa.Column('last_diagnosis_at', sa.DateTime(timezone=True), nullable=True, comment='最近一次诊断时间'),
    sa.Column('last_review_plan_id', sa.UUID(), nullable=True, comment='最近复习计划 ID'),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后一次预计算时间'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_user_profiles_user_course')
    )
    op.create_index(op.f('ix_user_profiles_course_id'), 'user_profiles', ['course_id'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_course_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_agent_sessions_user_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_course_id'), table_name='agent_sessions')
    op.drop_table('agent_sessions')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
