"""init 11 tables

Revision ID: 31e56328fb70
Revises: 
Create Date: 2026-06-12 19:02:24.284111
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31e56328fb70'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eval_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('eval_type', sa.String(length=32), nullable=False, comment='评估类型'),
    sa.Column('metric_name', sa.String(length=64), nullable=False, comment='评估指标名称'),
    sa.Column('metric_value', sa.Float(), nullable=False, comment='评估指标值'),
    sa.Column('sample_size', sa.Integer(), nullable=True, comment='样本数量'),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='附加信息'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False, comment='用户名'),
    sa.Column('password_hash', sa.String(length=256), nullable=False, comment='密码哈希值'),
    sa.Column('role', sa.String(length=16), nullable=False, comment='用户角色'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='课程名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='课程描述'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='创建者'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_created_by'), 'courses', ['created_by'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('file_type', sa.String(length=16), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('uploader_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_course_id'), 'documents', ['course_id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_uploader_id'), 'documents', ['uploader_id'], unique=False)
    op.create_table('knowledge_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False, comment='课程 ID'),
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='父节点 ID'),
    sa.Column('kp_path', sa.String(length=512), nullable=False, comment='知识点路径'),
    sa.Column('title', sa.String(length=256), nullable=False, comment='知识点标题'),
    sa.Column('summary', sa.Text(), nullable=True, comment='知识点摘要'),
    sa.Column('difficulty', sa.SmallInteger(), nullable=False, comment='知识点难度'),
    sa.Column('source', sa.String(length=32), nullable=False, comment='知识点来源'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序顺序'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_points_course_id'), 'knowledge_points', ['course_id'], unique=False)
    op.create_index(op.f('ix_knowledge_points_parent_id'), 'knowledge_points', ['parent_id'], unique=False)
    op.create_table('qa_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户 ID'),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('query', sa.Text(), nullable=False, comment='问题'),
    sa.Column('kp_path', sa.String(length=512), nullable=True, comment='知识点路径'),
    sa.Column('retrieved_units', sa.ARRAY(sa.UUID()), nullable=True, comment='检索到的单元 ID'),
    sa.Column('answer', sa.Text(), nullable=False, comment='答案'),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='参考来源'),
    sa.Column('feedback', sa.SmallInteger(), nullable=True, comment='用户反馈'),
    sa.Column('latency_ms', sa.Integer(), nullable=True, comment='处理耗时（毫秒）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_records_course_id'), 'qa_records', ['course_id'], unique=False)
    op.create_index(op.f('ix_qa_records_user_id'), 'qa_records', ['user_id'], unique=False)
    op.create_table('review_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='复习计划项'),
    sa.Column('reviewed_count', sa.SmallInteger(), nullable=False, comment='已复习数量'),
    sa.Column('total_count', sa.SmallInteger(), nullable=False, comment='总数量'),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='生成时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_plans_course_id'), 'review_plans', ['course_id'], unique=False)
    op.create_index(op.f('ix_review_plans_user_id'), 'review_plans', ['user_id'], unique=False)
    op.create_table('knowledge_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kp_id', sa.UUID(), nullable=False, comment='知识点 ID'),
    sa.Column('document_id', sa.UUID(), nullable=True, comment='文档 ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='内容'),
    sa.Column('summary', sa.Text(), nullable=True, comment='摘要'),
    sa.Column('seq_order', sa.Integer(), nullable=False, comment='在同一知识点内的顺序'),
    sa.Column('page_ref', sa.String(length=64), nullable=True, comment='页码引用'),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='元数据'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['kp_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_units_document_id'), 'knowledge_units', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_units_kp_id'), 'knowledge_units', ['kp_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kp_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=16), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_answer', sa.String(length=4), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.SmallInteger(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kp_id'], ['knowledge_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_kp_id'), 'questions', ['kp_id'], unique=False)
    op.create_index(op.f('ix_questions_source'), 'questions', ['source'], unique=False)
    op.create_index(op.f('ix_questions_verified'), 'questions', ['verified'], unique=False)
    op.create_table('practice_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('user_answer', sa.String(length=4), nullable=True, comment='用户答案'),
    sa.Column('correct_flag', sa.Boolean(), nullable=True, comment='对错标记'),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True, comment='提交答案时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_records_question_id'), 'practice_records', ['question_id'], unique=False)
    op.create_index(op.f('ix_practice_records_user_id'), 'practice_records', ['user_id'], unique=False)
    op.create_table('diagnosis_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('practice_record_id', sa.UUID(), nullable=False),
    sa.Column('error_reason', sa.Text(), nullable=False, comment='错误原因'),
    sa.Column('error_category', sa.String(length=32), nullable=False, comment='错误类别'),
    sa.Column('remedy_kp_ids', postgresql.ARRAY(sa.UUID()), nullable=True, comment='建议知识点 ID'),
    sa.Column('report_content', sa.Text(), nullable=False, comment='报告内容'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['practice_record_id'], ['practice_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_reports_practice_record_id'), 'diagnosis_reports', ['practice_record_id'], unique=False)
    op.create_index(op.f('ix_diagnosis_reports_user_id'), 'diagnosis_reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagnosis_reports_user_id'), table_name='diagnosis_reports')
    op.drop_index(op.f('ix_diagnosis_reports_practice_record_id'), table_name='diagnosis_reports')
    op.drop_table('diagnosis_reports')
    op.drop_index(op.f('ix_practice_records_user_id'), table_name='practice_records')
    op.drop_index(op.f('ix_practice_records_question_id'), table_name='practice_records')
    op.drop_table('practice_records')
    op.drop_index(op.f('ix_questions_verified'), table_name='questions')
    op.drop_index(op.f('ix_questions_source'), table_name='questions')
    op.drop_index(op.f('ix_questions_kp_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_knowledge_units_kp_id'), table_name='knowledge_units')
    op.drop_index(op.f('ix_knowledge_units_document_id'), table_name='knowledge_units')
    op.drop_table('knowledge_units')
    op.drop_index(op.f('ix_review_plans_user_id'), table_name='review_plans')
    op.drop_index(op.f('ix_review_plans_course_id'), table_name='review_plans')
    op.drop_table('review_plans')
    op.drop_index(op.f('ix_qa_records_user_id'), table_name='qa_records')
    op.drop_index(op.f('ix_qa_records_course_id'), table_name='qa_records')
    op.drop_table('qa_records')
    op.drop_index(op.f('ix_knowledge_points_parent_id'), table_name='knowledge_points')
    op.drop_index(op.f('ix_knowledge_points_course_id'), table_name='knowledge_points')
    op.drop_table('knowledge_points')
    op.drop_index(op.f('ix_documents_uploader_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_course_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_courses_created_by'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    op.drop_table('eval_metrics')
    # ### end Alembic commands ###
