"""add memory facts qa embedding importance for p2p5

Revision ID: 94e81d0d679b
Revises: a157c31e3aa5
Create Date: 2026-07-23 22:50:41.952730
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94e81d0d679b'
down_revision: Union[str, None] = 'a157c31e3aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('checkpoints_thread_id_idx'), table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index(op.f('checkpoint_writes_thread_id_idx'), table_name='checkpoint_writes')
    op.drop_table('checkpoint_writes')
    op.drop_table('checkpoint_migrations')
    op.drop_index(op.f('checkpoint_blobs_thread_id_idx'), table_name='checkpoint_blobs')
    op.drop_table('checkpoint_blobs')
    op.alter_column('agent_sessions', 'conversation',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment="多轮对话历史 [{'role', 'content', 'intent'}]",
               existing_comment='多轮对话历史',
               existing_nullable=True)
    op.alter_column('diagnosis_reports', 'overall_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='总体正确率',
               existing_nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('diagnosis_reports', 'total_practiced',
               existing_type=sa.INTEGER(),
               comment='总练习题目数',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('diagnosis_reports', 'weak_kps',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='薄弱知识点路径列表',
               existing_comment='薄弱知识点列表',
               existing_nullable=True)
    op.alter_column('diagnosis_reports', 'llm_analysis',
               existing_type=sa.TEXT(),
               comment='LLM 生成的深度分析',
               existing_comment='LLM 深度分析',
               existing_nullable=True)
    op.alter_column('diagnosis_reports', 'recommendations',
               existing_type=sa.TEXT(),
               comment='LLM 生成的学习建议',
               existing_comment='LLM 学习建议',
               existing_nullable=True)
    op.add_column('qa_records', sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=True, comment='query+answer 的 BGE-M3 dense 向量'))
    op.add_column('qa_records', sa.Column('importance', sa.Float(), nullable=True, comment='记忆重要性评分 0.0-1.0'))
    op.add_column('user_profiles', sa.Column('memory_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='L3 语义记忆：{"mastered_kps":[], "weak_kps":[], "common_mistakes":[], "learning_style":{}}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'memory_facts')
    op.drop_column('qa_records', 'importance')
    op.drop_column('qa_records', 'embedding')
    op.alter_column('diagnosis_reports', 'recommendations',
               existing_type=sa.TEXT(),
               comment='LLM 学习建议',
               existing_comment='LLM 生成的学习建议',
               existing_nullable=True)
    op.alter_column('diagnosis_reports', 'llm_analysis',
               existing_type=sa.TEXT(),
               comment='LLM 深度分析',
               existing_comment='LLM 生成的深度分析',
               existing_nullable=True)
    op.alter_column('diagnosis_reports', 'weak_kps',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='薄弱知识点列表',
               existing_comment='薄弱知识点路径列表',
               existing_nullable=True)
    op.alter_column('diagnosis_reports', 'total_practiced',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='总练习题目数',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('diagnosis_reports', 'overall_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='总体正确率',
               existing_nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('agent_sessions', 'conversation',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='多轮对话历史',
               existing_comment="多轮对话历史 [{'role', 'content', 'intent'}]",
               existing_nullable=True)
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    # ### end Alembic commands ###
